# Generated by Django 5.0 on 2023-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="recipe_image",
            field=models.ImageField(upload_to="recipe"),
        ),
    ]
